### ISSUE TITLE
pytorch版本requirements.py torch依赖 RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by chen-chen32** [lyuwenyu/RT-DETR#111]
我按照requirements.py 安装后出现以下报错 搜索看到可能与torch的版本有关。
Start training
Load PResNet50 state_dict
Initial lr:  [1e-05, 0.0001, 0.0001, 0.0001]
loading annotations into memory...
Done (t=11.22s)
creating index...
index created!
loading annotations into memory...
Done (t=0.38s)
creating index...
index created!
number of params: 42862860
Traceback (most recent call last):
  File "/home/chr/RT-DETR/rtdetr_pytorch/tools/train.py", line 48, in <module>
    main(args)
  File "/home/chr/RT-DETR/rtdetr_pytorch/tools/train.py", line 34, in main
    solver.fit()
  File "/home/chr/RT-DETR/rtdetr_pytorch/tools/../src/solver/det_solver.py", line 37, in fit
    train_stats = train_one_epoch(
  File "/home/chr/RT-DETR/rtdetr_pytorch/tools/../src/solver/det_engine.py", line 58, in train_one_epoch
    outputs = model(samples, targets)
  File "/home/public_conda/envs/rt_detr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chr/RT-DETR/rtdetr_pytorch/tools/../src/zoo/rtdetr/rtdetr.py", line 33, in forward
    x = self.backbone(x)
  File "/home/public_conda/envs/rt_detr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chr/RT-DETR/rtdetr_pytorch/tools/../src/nn/backbone/presnet.py", line 216, in forward
    conv1 = self.conv1(x)
  File "/home/public_conda/envs/rt_detr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/public_conda/envs/rt_detr/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/public_conda/envs/rt_detr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chr/RT-DETR/rtdetr_pytorch/tools/../src/nn/backbone/common.py", line 23, in forward
    return self.act(self.norm(self.conv(x)))
  File "/home/public_conda/envs/rt_detr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/public_conda/envs/rt_detr/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/public_conda/envs/rt_detr/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation

配置和安装的相关库
Mon Nov  6 12:16:44 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:04:00.0 Off |                  N/A |
|  0%   45C    P8    27W / 350W |     13MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:09:00.0 Off |                  N/A |
|  0%   43C    P8    25W / 350W |      3MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1834      G   /usr/bin/gnome-shell               10MiB |
+-----------------------------------------------------------------------------+

# packages in environment at /home/public_conda/envs/rt_detr:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
ca-certificates           2023.08.22           h06a4308_0  
certifi                   2023.7.22                pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
cmake                     3.27.7                   pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
contourpy                 1.2.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
flatbuffers               23.5.26                  pypi_0    pypi
fonttools                 4.44.0                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-resources       6.1.0                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
lit                       17.0.4                   pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.8.1                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  3.2.1                    pypi_0    pypi
numpy                     1.26.1                   pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
onnx                      1.14.0                   pypi_0    pypi
onnxruntime               1.15.1                   pypi_0    pypi
openssl                   3.0.12               h7f8727e_0  
packaging                 23.2                     pypi_0    pypi
pillow                    10.1.0                   pypi_0    pypi
pip                       23.3             py39h06a4308_0  
protobuf                  4.25.0                   pypi_0    pypi
pycocotools               2.0.7                    pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
python                    3.9.18               h955ad1f_0  
python-dateutil           2.8.2                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.31.0                   pypi_0    pypi
scipy                     1.11.3                   pypi_0    pypi
setuptools                68.0.0           py39h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
sympy                     1.12                     pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
torch                     2.0.1                    pypi_0    pypi
torchvision               0.15.2                   pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0  
urllib3                   2.0.7                    pypi_0    pypi
wheel                     0.41.2           py39h06a4308_0  
xz                        5.4.2                h5eee18b_0  
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0

**Comment by lyuwenyu** [comment]
可能你机器的`cuda`版本不支持`torch2.0.1`

**Comment by changzipeng** [comment]
cuda要升级到11.7
