### ISSUE TITLE
用RT-DETR训练AI-TOD

### ISSUE THREAD

**Issue by Claraeunice** [lyuwenyu/RT-DETR#158]
作者您好！我在使用RT-DETR-R50训练AI-TOD，出现报错：
`File "/root/RT-DETR/rtdetr_paddle/ppdet/data/source/coco.py", line 241, in parse_dataset  
  assert ct > 0, 'not found any coco record in %s' % (anno_path)
 AssertionError: not found any coco record in /root/autodl-tmp/AI-TOD/annotations/aitod_trainval_v1.json`

我的路径没有问题，数据集也是可用的，这是为什么呢？

是因为ppdet/data/source/category.py中没有AI-TOD数据集的类说明嘛？

**Comment by Claraeunice** [comment]
> 作者您好！我在使用RT-DETR-R50训练AI-TOD，出现报错： `[12/14 20:28:51] ppdet.data.source.coco WARNING: Illegal image file: /root/autodl-tmp/AI-TOD/train/3b444d792.png, and it will be ignored Traceback (most recent call last): File "tools/train.py", line 183, in <module> main() File "tools/train.py", line 179, in main run(FLAGS, cfg) File "tools/train.py", line 126, in run trainer = Trainer(cfg, mode='train') File "/root/RT-DETR/rtdetr_paddle/ppdet/engine/trainer.py", line 77, in __init__ self.loader = create('{}Reader'.format(capital_mode))( File "/root/RT-DETR/rtdetr_paddle/ppdet/data/reader.py", line 168, in __call__ self.dataset.parse_dataset() File "/root/RT-DETR/rtdetr_paddle/ppdet/data/source/coco.py", line 241, in parse_dataset assert ct > 0, 'not found any coco record in %s' % (anno_path) AssertionError: not found any coco record in /root/autodl-tmp/AI-TOD/annotations/aitod_trainval_v1.json `
> 
> 我的路径没有问题，数据集也是可用的，这是为什么呢？报告一堆图片是不合法的。
> 
> 是因为ppdet/data/source/category.py中没有AI-TOD数据集的类说明嘛？
![image](https://github.com/lyuwenyu/RT-DETR/assets/97581575/3ca247af-01e9-4f0c-a567-79d1f32b914f)

**Comment by lyuwenyu** [comment]
是coco的format嘛  另外图片都是png结尾的嘛

**Comment by todesti2** [comment]
> 是coco的format嘛 另外图片都是png结尾的嘛

是的！是COCO的格式，图片也都是png结尾，你看到的上面的图片信息报错只是其中一条，上面还有很多这样的信息。
不知道为什么，在其他任务上都可以跑这个AI-TOD

**Comment by lyuwenyu** [comment]
你要不用pytorch的跑一下试一试  用法一样的改一致数据集的路径就行了   看看是数据本身的问题还是代码的问题

**Comment by todesti2** [comment]
> 1. 先判断下 `/root/autodl-tmp/AI-TOD/train/3b444d792.png` 这路径对嘛
> 2. 要不用pytorch的跑一下试一试  用法一样的改一致数据集的路径就行了   看看是数据本身的问题还是代码的问题

不对，train文件下面还有一个images，images下面才是图片

**Comment by lyuwenyu** [comment]
<img width="300" alt="image" src="https://github.com/lyuwenyu/RT-DETR/assets/17582080/c2d04367-e074-4e07-9450-d0aee1d0c79d">

在这个位置改下 `train -> train/images` 就行了
