### ISSUE TITLE
我在更换数据集后发现如下问题

### ISSUE THREAD

**Issue by 1345149799** [lyuwenyu/RT-DETR#224]
Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\rtdetr\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "C:\Users\Administrator\.conda\envs\rtdetr\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "C:\Users\Administrator\.conda\envs\rtdetr\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "C:\Users\Administrator\.conda\envs\rtdetr\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\rtdetr\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\Administrator\.conda\envs\rtdetr\lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "C:\Users\Administrator\Desktop\code-lib\read-RT-DETR-main\rtdetr_pytorch\tools\..\src\data\dataloader.py", line 29, in default_collate_fn
    return torch.cat([x[0][None] for x in items], dim=0), [x[1] for x in items]
  File "C:\Users\Administrator\Desktop\code-lib\read-RT-DETR-main\rtdetr_pytorch\tools\..\src\data\dataloader.py", line 29, in <listcomp>
    return torch.cat([x[0][None] for x in items], dim=0), [x[1] for x in items]
TypeError: 'Image' object is not subscriptable

此问题在训练途中出现，怀疑是某个图片样本的错误，但调试信息不显示这一块的变量，我想不到有什么方法能够调试到它。
多次训练均出现此错误且不一定出现在第0个epoch的哪个位置，所以单步调试也非常困难。
数据集是crowdhuman，遵循coco格式修改的。

**Comment by 1345149799** [comment]
![image](https://github.com/lyuwenyu/RT-DETR/assets/88175171/c527c292-457d-4ca3-9ac8-e2b65a9cd4da)
![image](https://github.com/lyuwenyu/RT-DETR/assets/88175171/99d27d26-cebd-4f20-93f1-ce927a031990)
今天发现PIL图像经过transorm时发生了异常，但不清楚原因是否是图像size过大

**Comment by 1345149799** [comment]
traceback.print_exc()通过调用此函数发现返回输出为PIL.Image.DecompressionBombError: Image size (188418615 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.建议在异常处理中加上此函数，因为该错误难以追踪

**Comment by WaderLaken** [comment]
我也出现这个错误，根本没法训练，请问解决了吗？

PIL.Image.DecompressionBombError: Image size (181239234 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

**Comment by WaderLaken** [comment]
> 我也出现这个错误，根本没法训练，请问解决了吗？
> 
> PIL.Image.DecompressionBombError: Image size (181239234 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

而且我数据集图像最大分辨率6000x8000，不知道为啥会超出

**Comment by WaderLaken** [comment]
解决了，我自行修改了最大限制。

rtdetr_pytorch/src/data/transforms.py 文件添加如下代码：
```
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
Image.MAX_IMAGE_PIXELS = None
```

**Comment by Regina971** [comment]
同问

**Comment by zhuyy116** [comment]
> PIL.Image.DecompressionBombError: Image size (181239234 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

@1345149799 @WaderLaken @Regina971 @bryan-pakulski @lyuwenyu 

有人解决这个问题么？我的数据集最大分辨率1920*1080的，还是一直报错。使用coco数据集倒是没有这个错误，但是也会出现`RuntimeError: Too many open files. Communication with the workers is no longer possible.`

**Comment by proevgenii** [comment]
Same here
I saw suggestions to change limit by:
```
from PIL import Image
# Disable the decompression bomb warning (use with caution)
Image.MAX_IMAGE_PIXELS = None
```
And it should work

But I'm wondering why it's happening, my images relatively small and Image size reported in warning looks really weird
