### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by zHJ991014** [lyuwenyu/RT-DETR#260]
作者你好，请问我训练自己的训练集出现这个问题是什么原因
Traceback (most recent call last):
  File "C:\Users\zhanghaojie\Desktop\tarin\sourceofRT-DETR\RT-DETR-main\rtdetr_pytorch\tools\train.py", line 48, in <module>
    main(args)
  File "C:\Users\zhanghaojie\Desktop\tarin\sourceofRT-DETR\RT-DETR-main\rtdetr_pytorch\tools\train.py", line 34, in main
    solver.fit()
  File "C:\Users\zhanghaojie\Desktop\tarin\sourceofRT-DETR\RT-DETR-main\rtdetr_pytorch\tools\..\src\solver\det_solver.py", line 37, in fit
    train_stats = train_one_epoch(
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\zhanghaojie\Desktop\tarin\sourceofRT-DETR\RT-DETR-main\rtdetr_pytorch\tools\..\src\solver\det_engine.py", line 35, in train_one_epoch
    for samples, targets in metric_logger.log_every(data_loader, print_freq, header):
  File "C:\Users\zhanghaojie\Desktop\tarin\sourceofRT-DETR\RT-DETR-main\rtdetr_pytorch\tools\..\src\misc\logger.py", line 239, in log_every
    header, total_time_str, total_time / len(iterable)))
                            ~~~~~~~~~~~^~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero

**Comment by lyuwenyu** [comment]
数据没加载对吧   可以打印一下`dataset`的长度 看着像是是`0`
