### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by binghan-iOS** [lyuwenyu/RT-DETR#261]
root@hanbing-XPS-8960:/home/hanbing/project/RT-DETR/rtdetr_paddle# python3 tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml --eval
Error: Can not import paddle core while this file exists: /usr/local/lib/python3.10/dist-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/home/hanbing/project/RT-DETR/rtdetr_paddle/tools/train.py", line 30, in <module>
    import paddle
  File "/usr/local/lib/python3.10/dist-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.10/dist-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/core.py", line 338, in <module>
    raise e
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

**Comment by lyuwenyu** [comment]
貌似是paddle没安装对  请先根据机器的软件信息找到对应的`paddle`正确安装
