### ISSUE TITLE
RTDETR训练报错，求解

### ISSUE THREAD

**Issue by QianYing-LYG** [lyuwenyu/RT-DETR#344]
Not init distributed mode.
Initialized distributed mode...
Not init distributed mode.
Start training
Start training
Start training
Load PResNet50 state_dict
Load PResNet50 state_dict
Load PResNet50 state_dict

c101-Default-string:39325:39325 [0] bootstrap.cc:40 NCCL WARN Bootstrap : no socket interface found
c101-Default-string:39325:39325 [0] NCCL INFO init.cc:87 -> 3
c101-Default-string:39325:39325 [0] NCCL INFO init.cc:105 -> 3
Traceback (most recent call last):
  File "tools/train.py", line 48, in <module>
    main(args)
  File "tools/train.py", line 34, in main
    solver.fit()
  File "/home/c101/cvcode/LYG/RT-DETR/rtdetr_pytorch/tools/../src/solver/det_solver.py", line 21, in fit
    self.train()
  File "/home/c101/cvcode/LYG/RT-DETR/rtdetr_pytorch/tools/../src/solver/solver.py", line 45, in train
    self.setup()
  File "/home/c101/cvcode/LYG/RT-DETR/rtdetr_pytorch/tools/../src/solver/solver.py", line 28, in setup
    self.model = dist.warp_model(cfg.model.to(device), cfg.find_unused_parameters, cfg.sync_bn)
  File "/home/c101/cvcode/LYG/RT-DETR/rtdetr_pytorch/tools/../src/misc/dist.py", line 100, in warp_model
    model = DDP(model, device_ids=[rank], output_device=rank, find_unused_parameters=find_unused_parameters)
  File "/home/c101/anaconda3/envs/RTDETR/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/c101/anaconda3/envs/RTDETR/lib/python3.8/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1207, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
Bootstrap : no socket interface found
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 39326 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 39327 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 39328 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 39325) of binary: /home/c101/anaconda3/envs/RTDETR/bin/python
Traceback (most recent call last):
  File "/home/c101/anaconda3/envs/RTDETR/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/c101/anaconda3/envs/RTDETR/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/c101/anaconda3/envs/RTDETR/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/c101/anaconda3/envs/RTDETR/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/c101/anaconda3/envs/RTDETR/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/c101/anaconda3/envs/RTDETR/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-22_09:33:47
  host      : c101-Default-string
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 39325)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
================
============================================
训练报错如上，训练语句如下：export CUDA_VISIBLE_DEVICES=0,1 export NCCL_DEBUG=info export NCCL_SOCKET_IFNAME=eth0 export NCCL_IB_DISABLE=1
torchrun --nproc_per_node=4 tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml

**Comment by QianYing-LYG** [comment]
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.主要报错语句为这个
