### ISSUE TITLE
Problem with training on custom dataset - RT-DETR Pytorch

### ISSUE THREAD

**Issue by Sairam13001** [lyuwenyu/RT-DETR#346]
I am trying to train RT-DETR Pytorch on VisDrone dataset which has 10 classes. I converted the custom dataset's annotations to COCO format and changed the following: 

'img_folder' and 'ann_file' paths in RT-DETR/rtdetr_pytorch/configs/dataset/coco_detection.yml. 
num_classes = 10
remap_mscoco_category = False

And in RT-DETR/rtdetr_pytorch/src/data/coco/coco_dataset.py:
I replaced the mscoco_category2name with 
mscoco_category2name = {
    1: 'pedestrian',
    2: 'people',
    3: 'bicycle',
    4: 'car',
    5: 'van',
    6: 'truck',
    7: 'tricycle',
    8: 'awning-tricycle',
    9: 'bus',
    10: 'motor'
}

When I run the train.py file, I am getting the following error:

File "tools/train.py", line 35, in main
    solver.fit()
  File "/mnt/2C0EACF20EACB5EC/Token_Pruning/RT-DETR/rtdetr_pytorch/tools/../src/solver/det_solver.py", line 38, in fit
    train_stats = train_one_epoch(
  File "/mnt/2C0EACF20EACB5EC/Token_Pruning/RT-DETR/rtdetr_pytorch/tools/../src/solver/det_engine.py", line 58, in train_one_epoch
    outputs = model(samples, targets)
  File "/mnt/2C0EACF20EACB5EC/Miniconda3/envs/tp-aod/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/2C0EACF20EACB5EC/Token_Pruning/RT-DETR/rtdetr_pytorch/tools/../src/zoo/rtdetr/rtdetr.py", line 35, in forward
    x = self.decoder(x, targets)
  File "/mnt/2C0EACF20EACB5EC/Miniconda3/envs/tp-aod/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/2C0EACF20EACB5EC/Token_Pruning/RT-DETR/rtdetr_pytorch/tools/../src/zoo/rtdetr/rtdetr_decoder.py", line 537, in forward
    self._get_decoder_input(memory, spatial_shapes, denoising_class, denoising_bbox_unact)
  File "/mnt/2C0EACF20EACB5EC/Token_Pruning/RT-DETR/rtdetr_pytorch/tools/../src/zoo/rtdetr/rtdetr_decoder.py", line 479, in _get_decoder_input
    anchors, valid_mask = self._generate_anchors(spatial_shapes, device=memory.device)
  File "/mnt/2C0EACF20EACB5EC/Token_Pruning/RT-DETR/rtdetr_pytorch/tools/../src/zoo/rtdetr/rtdetr_decoder.py", line 461, in _generate_anchors
    anchors = torch.concat(anchors, 1).to(device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Another error is the Assertion error : assert (boxes1[:, 2:] >= boxes1[:, :2]).all()

Please let me know what might be the issue here

**Comment by Sairam13001** [comment]
And if I set the device to CPU, I am getting this error:

Traceback (most recent call last):
  File "tools/train.py", line 49, in <module>
    main(args)
  File "tools/train.py", line 35, in main
    solver.fit()
  File "/mnt/2C0EACF20EACB5EC/Token_Pruning/RT-DETR/rtdetr_pytorch/tools/../src/solver/det_solver.py", line 38, in fit
    train_stats = train_one_epoch(
  File "/mnt/2C0EACF20EACB5EC/Token_Pruning/RT-DETR/rtdetr_pytorch/tools/../src/solver/det_engine.py", line 58, in train_one_epoch
    outputs = model(samples, targets)
  File "/mnt/2C0EACF20EACB5EC/Miniconda3/envs/tp-aod/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/2C0EACF20EACB5EC/Token_Pruning/RT-DETR/rtdetr_pytorch/tools/../src/zoo/rtdetr/rtdetr.py", line 35, in forward
    x = self.decoder(x, targets)
  File "/mnt/2C0EACF20EACB5EC/Miniconda3/envs/tp-aod/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/2C0EACF20EACB5EC/Token_Pruning/RT-DETR/rtdetr_pytorch/tools/../src/zoo/rtdetr/rtdetr_decoder.py", line 526, in forward
    get_contrastive_denoising_training_group(targets, \
  File "/mnt/2C0EACF20EACB5EC/Token_Pruning/RT-DETR/rtdetr_pytorch/tools/../src/zoo/rtdetr/denoising.py", line 97, in get_contrastive_denoising_training_group
    input_query_class = class_embed(input_query_class)
  File "/mnt/2C0EACF20EACB5EC/Miniconda3/envs/tp-aod/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/2C0EACF20EACB5EC/Miniconda3/envs/tp-aod/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/mnt/2C0EACF20EACB5EC/Miniconda3/envs/tp-aod/lib/python3.8/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

**Comment by lyuwenyu** [comment]
> mscoco_category2name = {
> 1: 'pedestrian',
> 2: 'people',
> 3: 'bicycle',
> 4: 'car',
> 5: 'van',
> 6: 'truck',
> 7: 'tricycle',
> 8: 'awning-tricycle',
> 9: 'bus',
> 10: 'motor'
> }


 start from 0

**Comment by lyuwenyu** [comment]
> num_classes = 10 remap_mscoco_category = False
> 
> And in RT-DETR/rtdetr_pytorch/src/data/coco/coco_dataset.py: I replaced the mscoco_category2name with mscoco_category2name = { 1: 'pedestrian', 2: 'people', 3: 'bicycle', 4: 'car', 5: 'van', 6: 'truck', 7: 'tricycle', 8: 'awning-tricycle', 9: 'bus', 10: 'motor' }

try to start from 0

**Comment by Sairam13001** [comment]
Thank you very much. It worked with `remap_mscoco_category = True` with my custom mscoco_category2name.

**Comment by Sairam13001** [comment]
I have another query. I am resizing my custom dataset images to a size of 1024 x 1024. I am starting from your COCO trained model weights [url](https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetr_r50vd_6x_coco_from_paddle.pth) and tuning on my custom dataset. After training for an epoch, during the validation, I am getting this following error:

RuntimeError: The size of tensor a (1024) must match the size of tensor b (400) at non-singleton dimension 1                                         
Traceback (most recent call last):                                                                                                                   
  File "/data/Sairam/RT-DETR/rtdetr_pytorch/tools/train.py", line 56, in <module>                                                                    
    main(args)                                                                                                                                       
  File "/data/Sairam/RT-DETR/rtdetr_pytorch/tools/train.py", line 40, in main                                                                        
    solver.val()                                                                                                                                     
  File "/data/Sairam/RT-DETR/rtdetr_pytorch/tools/../src/solver/det_solver.py", line 98, in val                                                      
    test_stats, coco_evaluator = evaluate(module, self.criterion, self.postprocessor,                                                                
  File "/home/srikar/data/anaconda3/envs/rt-detr/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context              
    return func(*args, **kwargs)                                                                                                                     
  File "/data/Sairam/RT-DETR/rtdetr_pytorch/tools/../src/solver/det_engine.py", line 142, in evaluate                                                
    outputs = model(samples)                                                                                                                         
  File "/home/srikar/data/anaconda3/envs/rt-detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl                   
    return forward_call(*args, **kwargs)                                                                                                             
  File "/data/Sairam/RT-DETR/rtdetr_pytorch/tools/../src/zoo/rtdetr/rtdetr.py", line 34, in forward                                                  
    x = self.encoder(x)                                                                                                                              
  File "/home/srikar/data/anaconda3/envs/rt-detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl                   
    return forward_call(*args, **kwargs)                                                                                                             
  File "/data/Sairam/RT-DETR/rtdetr_pytorch/tools/../src/zoo/rtdetr/hybrid_encoder.py", line 301, in forward                                         
    memory = self.encoder[i](src_flatten, pos_embed=pos_embed)                                                                                       
  File "/home/srikar/data/anaconda3/envs/rt-detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl                   
    return forward_call(*args, **kwargs)                                                                                                             
  File "/data/Sairam/RT-DETR/rtdetr_pytorch/tools/../src/zoo/rtdetr/hybrid_encoder.py", line 176, in forward                                         
    output = layer(output, src_mask=src_mask, pos_embed=pos_embed)                                                                                   
  File "/home/srikar/data/anaconda3/envs/rt-detr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl                   
    return forward_call(*args, **kwargs)                                                                                                             
  File "/data/Sairam/RT-DETR/rtdetr_pytorch/tools/../src/zoo/rtdetr/hybrid_encoder.py", line 149, in forward                                         
    q = k = self.with_pos_embed(src, pos_embed)                                                                                                      
  File "/data/Sairam/RT-DETR/rtdetr_pytorch/tools/../src/zoo/rtdetr/hybrid_encoder.py", line 143, in with_pos_embed                                  
    return tensor if pos_embed is None else tensor + pos_embed                                                                                       
RuntimeError: The size of tensor a (1024) must match the size of tensor b (400) at non-singleton dimension 1

Please let me know what might be causing the issue.
