### ISSUE TITLE
KeyError: '_pymodule'

### ISSUE THREAD

**Issue by m7mdhka** [lyuwenyu/RT-DETR#391]
I got this error:
Traceback (most recent call last):
  File "C:\Users\m.rahamneh\Documents\MiTool\det\app\detection\model_hub\rtdetrv2\rtdetrv2_torch.py", line 83, in <module>
    main(args)
  File "C:\Users\m.rahamneh\Documents\MiTool\det\app\detection\model_hub\rtdetrv2\rtdetrv2_torch.py", line 44, in main
    cfg.model.load_state_dict(state)
  File "C:\Users\m.rahamneh\Documents\MiTool\det\app\detection\model_hub\rtdetrv2\core\yaml_config.py", line 36, in model
    self._model = create(self.yaml_cfg['model'], self.global_cfg)
  File "C:\Users\m.rahamneh\Documents\MiTool\det\app\detection\model_hub\rtdetrv2\core\workspace.py", line 121, in create
    module = getattr(cfg['_pymodule'], name)
KeyError: '_pymodule'

**Comment by lyuwenyu** [comment]
```
cd  RT-DETR/rtdetrv2_pytorch

python tools/train.py -c path/to/config

```

**Comment by anewcatwhy** [comment]
> ```
> cd  RT-DETR/rtdetrv2_pytorch
> 
> python tools/train.py -c path/to/config
> ```

I'm sorry that I can't understand it,why do that(苦笑)
I have the same question,and it really does't have other methods

**Comment by anewcatwhy** [comment]
> ```
> cd  RT-DETR/rtdetrv2_pytorch
> 
> python tools/train.py -c path/to/config
> ```

I'm sorry that I can't understand it,why do that(苦笑)
I have the same question,and it really does't have other methods
