### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by lqh964165950** [lyuwenyu/RT-DETR#392]
Not init distributed mode.
Traceback (most recent call last):
  File "train.py", line 50, in <module>
    main(args)
  File "train.py", line 24, in main
    cfg = YAMLConfig(
  File "/home/gxu4090x2/桌面/lqh/program/RT-DETR-main/rtdetr_pytorch/tools/../src/core/yaml_config.py", line 18, in __init__
    cfg = load_config(cfg_path)
  File "/home/gxu4090x2/桌面/lqh/program/RT-DETR-main/rtdetr_pytorch/tools/../src/core/yaml_utils.py", line 155, in load_config
    _, ext = os.path.splitext(file_path)
  File "/home/gxu4090x2/.conda/envs/lqh/lib/python3.8/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by lyuwenyu** [comment]
```
cd  RT-DETR/rtdetrv2_pytorch

python tools/train.py -c path/to/config

```

**Comment by lqh964165950** [comment]
请问一下，用自己的数据集训练rtdetr_r101vd_6x_coco模型，为什么无法在output文件夹得到输出结果？

**Comment by lyuwenyu** [comment]
有训练一个完整的吧epoch嘛
