### ISSUE TITLE
训练报错，请问这个怎么解决

### ISSUE THREAD

**Issue by qq3399476669** [lyuwenyu/RT-DETR#414]
Not init distributed mode.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\detr\rt-detr\RT-DETR-main\rtdetrv2_pytorch\tools\train.py", line 65, in <module>
    main(args)
  File "C:\Users\Administrator\Desktop\detr\rt-detr\RT-DETR-main\rtdetrv2_pytorch\tools\train.py", line 27, in main
    cfg = YAMLConfig(args.config, **update_dict)
  File "C:\Users\Administrator\Desktop\detr\rt-detr\RT-DETR-main\rtdetrv2_pytorch\tools\..\src\core\yaml_config.py", line 20, in __init__
    cfg = load_config(cfg_path)
  File "C:\Users\Administrator\Desktop\detr\rt-detr\RT-DETR-main\rtdetrv2_pytorch\tools\..\src\core\yaml_utils.py", line 29, in load_config
    file_cfg = yaml.load(f, Loader=yaml.Loader)
  File "D:\Anaconda3\envs\RT-DETR\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "D:\Anaconda3\envs\RT-DETR\lib\site-packages\yaml\loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "D:\Anaconda3\envs\RT-DETR\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "D:\Anaconda3\envs\RT-DETR\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "D:\Anaconda3\envs\RT-DETR\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0x86 in position 392: illegal multibyte sequence

**Comment by bleudeprusse** [comment]
你好，我也遇到了相同的问题，请问你解决了吗
