### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cleanup'

### ISSUE THREAD

**Issue by xinyuzhang1026** [lyuwenyu/RT-DETR#415]
RT-DETRv2 error: AttributeError: 'NoneType' object has no attribute 'cleanup'

Traceback (most recent call last):
  File "C:/Users/userone/Desktop/rtdetrv2_pytorch/tools/train.py", line 65, in <module>
    main(args)
  File "C:/Users/userone/Desktop/rtdetrv2_pytorch/tools/train.py", line 35, in main
    solver.fit()
  File "C:\Users\userone\Desktop\rtdetrv2_pytorch\tools\..\src\solver\det_solver.py", line 67, in fit
    test_stats, coco_evaluator = evaluate(
  File "C:\Users\userone\.conda\envs\RT\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\userone\Desktop\rtdetrv2_pytorch\tools\..\src\solver\det_engine.py", line 110, in evaluate
    coco_evaluator.cleanup()
**AttributeError: 'NoneType' object has no attribute 'cleanup'**

**Comment by xinyuzhang1026** [comment]
I have found the problem,I use RTDETR's coco_detection.yml instead RTDETRv2's coco_detection.yml，but they are different.
