### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'D:/RT-DETR-main/RT-data/coco/images/T\\000000520479.jpg'

### ISSUE THREAD

**Issue by zouchao8527** [lyuwenyu/RT-DETR#499]
为了快速跑通，训练集数据很少，就只有29个图片，然后训练时出现了找不到图片的报错，关键是报错的图片根本不在我的数据集里面，莫名其妙
<img width="905" alt="1" src="https://github.com/user-attachments/assets/4d8210a0-fd37-485d-b122-3e3789bfa36a">

**Comment by lyuwenyu** [comment]
什么意思 `T`这个目录本来没有？ 还是说`xxxx.jpg`没有

另外可以把你数据的`config`贴一下

**Comment by zouchao8527** [comment]
> 什么意思`T`这个目录本来没有？还是说`xxxx.jpg`没有
> 
> 另外可以把你数据的`config`贴一下
  
谢谢，这个问题解决了，但是又出现了新错误，因为我测试的是3分类，所以只在coco.detection.yml中将num_classes改为了3，其他没有动，是不是分类命名没有更改的原因呢？我记得YOLO检测在对分类更改时还需要对分类的命名进行更改，您的这个模型不需要吗？或者需要更改在哪里改呢，我没有找到？以下是报错信息，希望您能回复一下，谢谢！

C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [59,0,0], thread: [61,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [59,0,0], thread: [62,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Indexing.cu:1146: block: [59,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "D:\RT-DETR-main\RT-DETR-main\rtdetr_pytorch\tools\train.py", line 50, in <module>
    main(args)
  File "D:\RT-DETR-main\RT-DETR-main\rtdetr_pytorch\tools\train.py", line 36, in main
    solver.fit()
  File "D:\RT-DETR-main\RT-DETR-main\rtdetr_pytorch\tools\..\src\solver\det_solver.py", line 37, in fit
    train_stats = train_one_epoch(
  File "D:\RT-DETR-main\RT-DETR-main\rtdetr_pytorch\tools\..\src\solver\det_engine.py", line 58, in train_one_epoch
    outputs = model(samples, targets)
  File "D:\code\anaconda3\envs\RT-DETR\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\RT-DETR-main\RT-DETR-main\rtdetr_pytorch\tools\..\src\zoo\rtdetr\rtdetr.py", line 35, in forward
    x = self.decoder(x, targets)
  File "D:\code\anaconda3\envs\RT-DETR\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\RT-DETR-main\RT-DETR-main\rtdetr_pytorch\tools\..\src\zoo\rtdetr\rtdetr_decoder.py", line 537, in forward
    self._get_decoder_input(memory, spatial_shapes, denoising_class, denoising_bbox_unact)
  File "D:\RT-DETR-main\RT-DETR-main\rtdetr_pytorch\tools\..\src\zoo\rtdetr\rtdetr_decoder.py", line 479, in _get_decoder_input
    anchors, valid_mask = self._generate_anchors(spatial_shapes, device=memory.device)
  File "D:\RT-DETR-main\RT-DETR-main\rtdetr_pytorch\tools\..\src\zoo\rtdetr\rtdetr_decoder.py", line 461, in _generate_anchors
    anchors = torch.concat(anchors, 1).to(device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by desperate214** [comment]
> 我也遇到了这个问题，我用的数据集是coco2017的数据集，报错显示说在val2017里面找不到00000009.jpg，但是这个图片在train2017里面。以下是报错信息，想询问一下您是怎么就解决的，希望您能回复一下，谢谢！
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\admin\PycharmProjects\my_rt-detr\src\data\coco\val2017\000000000009.jpg'

解决了吗，怎么解决的？

**Comment by wg231** [comment]
路径有问题
