### ISSUE TITLE
Issue with training on user data

### ISSUE THREAD

**Issue by aiexperts-andreas** [lyuwenyu/RT-DETR#52]
I get this error message when I attempt to train. I have all my images in train and val folders, and my annotations in coco format as json files. I don't know why I get this error message.

python tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml
Traceback (most recent call last):
  File "C:\Users\copyc\AiExperts\Eide\RT-DETR\rtdetr_pytorch\tools\train.py", line 9, in <module>
    import src.misc.dist as dist
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\copyc\AiExperts\Eide\RT-DETR\rtdetr_pytorch\tools\..\src\__init__.py", line 2, in <module>
    from . import data
    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\copyc\AiExperts\Eide\RT-DETR\rtdetr_pytorch\tools\..\src\data\__init__.py", line 6, in <module>
    from .transforms import *
  File "C:\Users\copyc\AiExperts\Eide\RT-DETR\rtdetr_pytorch\tools\..\src\data\transforms.py", line 30, in <module>
    ConvertDtype = register(T.ConvertDtype)
                            ^^^^^^^^^^^^^^
AttributeError: module 'torchvision.transforms.v2' has no attribute 'ConvertDtype'. Did you mean: 'ConvertImageDtype'?

**Comment by lyuwenyu** [comment]
Please use this torchvision version. It has [ConvertDtype]. (https://github.com/pytorch/vision/blob/v0.15.2/torchvision/transforms/v2/_meta.py#L34) 
```
torch                              2.0.1
torchvision                        0.15.2
```

**Comment by aiexperts-andreas** [comment]
Changed versions and got this now?

python tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml

Not init distributed mode.
Start training
Load PResNet50 state_dict
Initial lr:  [1e-05, 0.0001, 0.0001, 0.0001]
Traceback (most recent call last):
  File "C:\Users\copyc\AiExperts\Eide\RT-DETR\rtdetr_pytorch\tools\train.py", line 38, in <module>
    main(args)
  File "C:\Users\copyc\AiExperts\Eide\RT-DETR\rtdetr_pytorch\tools\train.py", line 24, in main
    solver.fit()
  File "C:\Users\copyc\AiExperts\Eide\RT-DETR\rtdetr_pytorch\tools\..\src\solver\det_solver.py", line 21, in fit
    self.train()
  File "C:\Users\copyc\AiExperts\Eide\RT-DETR\rtdetr_pytorch\tools\..\src\solver\solver.py", line 48, in train
    self.train_dataloader = dist.warp_loader(self.cfg.train_dataloader, \
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\copyc\AiExperts\Eide\RT-DETR\rtdetr_pytorch\tools\..\src\core\yaml_config.py", line 83, in train_dataloader
    self._train_dataloader = create('train_dataloader')
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\copyc\AiExperts\Eide\RT-DETR\rtdetr_pytorch\tools\..\src\core\yaml_utils.py", line 95, in create
    cls = getattr(cfg['_pymodule'], name)
                  ~~~^^^^^^^^^^^^^
KeyError: '_pymodule'

**Comment by szmate00** [comment]
@aiexperts-andreas could you please share with us how you managed to solve the KeyError:'_pymodule'?
