### ISSUE TITLE
flops计算代码跑不通

### ISSUE THREAD

**Issue by leoxxxxxD** [lyuwenyu/RT-DETR#72]
paddle2.5，看了下paddle的dynamic_flops函数，和示例对不上。

**Comment by Claraeunice** [comment]
> paddle2.5，看了下paddle的dynamic_flops函数，和示例对不上。
我也跑不通参数量和计算量代码，请问你解决了吗

**Comment by Claraeunice** [comment]
> paddle2.5，看了下paddle的dynamic_flops函数，和示例对不上。

我也跑不通参数量和计算量代码，请问你解决了吗

**Comment by lyuwenyu** [comment]
按照这个文档修改代码了嘛 
![image](https://github.com/lyuwenyu/RT-DETR/assets/17582080/4a28ca86-9bd5-4103-9391-fb5bdbe1f068)

**Comment by Claraeunice** [comment]
> 按照这个文档修改代码了嘛 ![image](https://user-images.githubusercontent.com/17582080/273757280-4a28ca86-9bd5-4103-9391-fb5bdbe1f068.png)

是的，但是执行示例代码会有报错
`Traceback (most recent call last):
  File "floap.py", line 14, in <module>
    paddle.flops(model, None, blob, custom_ops=None, print_detail=False)
TypeError: flops() got multiple values for argument 'custom_ops'`

**Comment by Claraeunice** [comment]
> 按照这个文档修改代码了嘛 ![image](https://user-images.githubusercontent.com/17582080/273757280-4a28ca86-9bd5-4103-9391-fb5bdbe1f068.png)

如果为了解决这个报错删除掉执行代码中的参数custom_ops=None,
就会出现新的报错
`Traceback (most recent call last):
  File "floap.py", line 14, in <module>
    paddle.flops(model, None, blob,  print_detail=False)
  File "/root/miniconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/hapi/dynamic_flops.py", line 111, in flops
    inputs = paddle.randn(input_size)
  File "/root/miniconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/tensor/random.py", line 479, in randn
    return standard_normal(shape, dtype, name)
  File "/root/miniconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/tensor/random.py", line 427, in standard_normal
    return gaussian(shape=shape, mean=0.0, std=1.0, dtype=dtype, name=name)
  File "/root/miniconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/tensor/random.py", line 344, in gaussian
    shape = paddle.utils.convert_shape_to_list(shape)
  File "/root/miniconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/utils/layers_utils.py", line 459, in convert_shape_to_list
    shape = shape.astype(int).tolist()
AttributeError: 'NoneType' object has no attribute 'astype'`

**Comment by lyuwenyu** [comment]
跑下面这个代码有问题？ 你得保证input_size和inputs有一个输入


![image](https://github.com/lyuwenyu/RT-DETR/assets/17582080/f2a17f07-94c8-4573-ba5d-cce94305f77d)

**Comment by Claraeunice** [comment]
> 你得保证input_size和inputs有一个输入

“你得保证input_size和inputs有一个输入”：您的意思是我需要手动修改`paddle.flops(model, None, blob, custom_ops=None, print_detail=False)`中的 None和blob嘛，但是我并不知道要输入什么呢。
我是按照操作说明，将执行代码放入新建的python文件并执行该文件的
紧接着出现上面报错

**Comment by lyuwenyu** [comment]
blob的内容上边不是有例子嘛

**Comment by Claraeunice** [comment]
> blob的内容上边不是有例子嘛

呜呜，小白表示没看懂是怎么操作

**Comment by Claraeunice** [comment]
> blob的内容上边不是有例子嘛

好多天了没搞明白，恳请您再详细一点┭┮﹏┭┮万分感谢

**Comment by lyuwenyu** [comment]
你先直接copy文档中的代码 看看能不能跑通

**Comment by Claraeunice** [comment]
> 你先直接copy文档中的代码 看看能不能跑通

是的，把文档中的代码放到新建python文件中，执行后出现了上面的报错

**Comment by lyuwenyu** [comment]
```
>>> from ppdet.core.workspace import create
>>> cfg_path = './configs/rtdetr/rtdetr_r50vd_6x_coco.yml'
>>> cfg = load_config(cfg_path)
>>> model = create(cfg.architecture)
W1013 11:44:18.187057 15003 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 12.0, Runtime API Version: 10.2
W1013 11:44:18.195801 15003 gpu_resources.cc:149] device: 0, cuDNN Version: 7.6.
>>> 
>>> blob = {
...     'image': paddle.randn([1, 3, 640, 640]),
...     'im_shape': paddle.to_tensor([[640, 640]]),
...     'scale_factor': paddle.to_tensor([[1., 1.]])
... }
>>> paddle.flops(model, None, blob, custom_ops=None, print_detail=False)
...
...
...
Total Flops: 68348108800     Total Params: 41514204
68348108800
>>> 
>>> paddle.__version__
'2.5.0'

```

**Comment by Claraeunice** [comment]
> 并没有什么问题 检查一下自己的操作流程吧
> 
> ```
> >>> from ppdet.core.workspace import create
> >>> cfg_path = './configs/rtdetr/rtdetr_r50vd_6x_coco.yml'
> >>> cfg = load_config(cfg_path)
> >>> model = create(cfg.architecture)
> W1013 11:44:18.187057 15003 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 12.0, Runtime API Version: 10.2
> W1013 11:44:18.195801 15003 gpu_resources.cc:149] device: 0, cuDNN Version: 7.6.
> >>> 
> >>> blob = {
> ...     'image': paddle.randn([1, 3, 640, 640]),
> ...     'im_shape': paddle.to_tensor([[640, 640]]),
> ...     'scale_factor': paddle.to_tensor([[1., 1.]])
> ... }
> >>> paddle.flops(model, None, blob, custom_ops=None, print_detail=False)
> ...
> ...
> ...
> Total Flops: 68348108800     Total Params: 41514204
> 68348108800
> >>> 
> >>> paddle.__version__
> '2.5.0'
> ```

好的，我试试，非常感谢您耐心的回复

**Comment by JianyuChenyyds** [comment]
> 按照这个文档修改代码了嘛 ![image](https://user-images.githubusercontent.com/17582080/273757280-4a28ca86-9bd5-4103-9391-fb5bdbe1f068.png)

按这个代码修改后的FLOPs跟Model ZOO上对不上啊

**Comment by Claraeunice** [comment]
> 并没有什么问题 检查一下自己的操作流程吧
> 
> ```
> >>> from ppdet.core.workspace import create
> >>> cfg_path = './configs/rtdetr/rtdetr_r50vd_6x_coco.yml'
> >>> cfg = load_config(cfg_path)
> >>> model = create(cfg.architecture)
> W1013 11:44:18.187057 15003 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 12.0, Runtime API Version: 10.2
> W1013 11:44:18.195801 15003 gpu_resources.cc:149] device: 0, cuDNN Version: 7.6.
> >>> 
> >>> blob = {
> ...     'image': paddle.randn([1, 3, 640, 640]),
> ...     'im_shape': paddle.to_tensor([[640, 640]]),
> ...     'scale_factor': paddle.to_tensor([[1., 1.]])
> ... }
> >>> paddle.flops(model, None, blob, custom_ops=None, print_detail=False)
> ...
> ...
> ...
> Total Flops: 68348108800     Total Params: 41514204
> 68348108800
> >>> 
> >>> paddle.__version__
> '2.5.0'
> ```

您好，还是跑不通，是要更改什么吗

**Comment by Claraeunice** [comment]
> cfg = load_config(cfg_path)

按照这个跑出来是

`Traceback (most recent call last):
  File "flops.py", line 16, in <module>
    paddle.flops(model, None,blob, custom_ops=None, print_detail=False)

TypeError: flops() got multiple values for argument 'custom_ops'`

**Comment by Claraeunice** [comment]
> > 按照这个文档修改代码了嘛 ![image](https://user-images.githubusercontent.com/17582080/273757280-4a28ca86-9bd5-4103-9391-fb5bdbe1f068.png)
> 
> 按这个代码修改后的FLOPs跟Model ZOO上对不上啊

是的  我也跑不出来

**Comment by lyuwenyu** [comment]
请按照文档操作....   我这边没啥问题

```
In [1]: import paddle
   ...: from ppdet.core.workspace import load_config, merge_config
   ...: from ppdet.core.workspace import create
   ...:
   ...: cfg_path = './configs/rtdetr/rtdetr_r50vd_6x_coco.yml'
   ...: cfg = load_config(cfg_path)
   ...: model = create(cfg.architecture)
   ...:
   ...: blob = {
   ...:     'image': paddle.randn([1, 3, 640, 640]),
   ...:     'im_shape': paddle.to_tensor([[640, 640]]),
   ...:     'scale_factor': paddle.to_tensor([[1., 1.]])
   ...: }
   ...: paddle.flops(model, None, blob, custom_ops=None, print_detail=False)
   ...:
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
W1026 03:41:48.273075 55687 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version:12.0, Runtime API Version: 11.7
W1026 03:41:48.281303 55687 gpu_resources.cc:149] device: 0, cuDNN Version: 8.4.
<class 'paddle.nn.layer.conv.Conv2D'>'s flops has been counted
<class 'paddle.nn.layer.norm.BatchNorm2D'>'s flops has been counted
<class 'paddle.nn.layer.pooling.AvgPool2D'>'s flops has been counted
<class 'paddle.nn.layer.common.Linear'>'s flops has been counted
<class 'paddle.nn.layer.common.Dropout'>'s flops has been counted
Cannot find suitable count function for <class 'paddle.nn.layer.norm.LayerNorm'>. Treat it as zero FLOPs.
Cannot find suitable count function for <class 'paddle.nn.layer.common.Embedding'>. Treat it as zero FLOPs.
Cannot find suitable count function for <class 'ppdet.modeling.transformers.matchers.HungarianMatcher'>. Treat it as zero FLOPs.
Cannot find suitable count function for <class 'paddle.nn.layer.common.Identity'>. Treat it as zero FLOPs.
Total Flops: 68982860800     Total Params: 41660694
Out[1]: 68982860800

In [2]: import paddle
   ...: from ppdet.core.workspace import load_config, merge_config
   ...: from ppdet.core.workspace import create
   ...:
   ...: cfg_path = './configs/rtdetr/rtdetr_r18vd_6x_coco.yml'
   ...: cfg = load_config(cfg_path)
   ...: model = create(cfg.architecture)
   ...:
   ...: blob = {
   ...:     'image': paddle.randn([1, 3, 640, 640]),
   ...:     'im_shape': paddle.to_tensor([[640, 640]]),
   ...:     'scale_factor': paddle.to_tensor([[1., 1.]])
   ...: }
   ...: paddle.flops(model, None, blob, custom_ops=None, print_detail=False)
   ...:
<class 'paddle.nn.layer.conv.Conv2D'>'s flops has been counted
<class 'paddle.nn.layer.norm.BatchNorm2D'>'s flops has been counted
<class 'paddle.nn.layer.pooling.AvgPool2D'>'s flops has been counted
<class 'paddle.nn.layer.common.Linear'>'s flops has been counted
<class 'paddle.nn.layer.common.Dropout'>'s flops has been counted
Cannot find suitable count function for <class 'paddle.nn.layer.norm.LayerNorm'>. Treat it as zero FLOPs.
Cannot find suitable count function for <class 'paddle.nn.layer.common.Embedding'>. Treat it as zero FLOPs.
Cannot find suitable count function for <class 'ppdet.modeling.transformers.matchers.HungarianMatcher'>. Treat it as zero FLOPs.
Total Flops: 30996761600     Total Params: 19504810
Out[2]: 30996761600

```

**Comment by lyuwenyu** [comment]
> > 按照这个文档修改代码了嘛 ![image](https://user-images.githubusercontent.com/17582080/273757280-4a28ca86-9bd5-4103-9391-fb5bdbe1f068.png)
> 
> 按这个代码修改后的FLOPs跟Model ZOO上对不上啊

请先理解 `FLOPs`和 `MACs`的区别

**Comment by JianyuChenyyds** [comment]
> > > 按照这个文档修改代码了嘛 ![image](https://user-images.githubusercontent.com/17582080/273757280-4a28ca86-9bd5-4103-9391-fb5bdbe1f068.png)
> > 
> > 
> > 按这个代码修改后的FLOPs跟Model ZOO上对不上啊
> 
> 请先理解 `FLOPs`和 `MACs`的区别

是不是要再×2

**Comment by Claraeunice** [comment]
> > > > 按照这个文档修改代码了嘛 ![image](https://user-images.githubusercontent.com/17582080/273757280-4a28ca86-9bd5-4103-9391-fb5bdbe1f068.png)
> > > 
> > > 
> > > 按这个代码修改后的FLOPs跟Model ZOO上对不上啊
> > 
> > 
> > 请先理解 `FLOPs`和 `MACs`的区别
> 
> 是不是要再×2

朋友，你能跑这份代码吗？

**Comment by Claraeunice** [comment]
> 请按照文档操作.... 我这边没啥问题 @Claraeunice
> 
> ```
> In [1]: import paddle
>    ...: from ppdet.core.workspace import load_config, merge_config
>    ...: from ppdet.core.workspace import create
>    ...:
>    ...: cfg_path = './configs/rtdetr/rtdetr_r50vd_6x_coco.yml'
>    ...: cfg = load_config(cfg_path)
>    ...: model = create(cfg.architecture)
>    ...:
>    ...: blob = {
>    ...:     'image': paddle.randn([1, 3, 640, 640]),
>    ...:     'im_shape': paddle.to_tensor([[640, 640]]),
>    ...:     'scale_factor': paddle.to_tensor([[1., 1.]])
>    ...: }
>    ...: paddle.flops(model, None, blob, custom_ops=None, print_detail=False)
>    ...:
> grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
> W1026 03:41:48.273075 55687 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version:12.0, Runtime API Version: 11.7
> W1026 03:41:48.281303 55687 gpu_resources.cc:149] device: 0, cuDNN Version: 8.4.
> <class 'paddle.nn.layer.conv.Conv2D'>'s flops has been counted
> <class 'paddle.nn.layer.norm.BatchNorm2D'>'s flops has been counted
> <class 'paddle.nn.layer.pooling.AvgPool2D'>'s flops has been counted
> <class 'paddle.nn.layer.common.Linear'>'s flops has been counted
> <class 'paddle.nn.layer.common.Dropout'>'s flops has been counted
> Cannot find suitable count function for <class 'paddle.nn.layer.norm.LayerNorm'>. Treat it as zero FLOPs.
> Cannot find suitable count function for <class 'paddle.nn.layer.common.Embedding'>. Treat it as zero FLOPs.
> Cannot find suitable count function for <class 'ppdet.modeling.transformers.matchers.HungarianMatcher'>. Treat it as zero FLOPs.
> Cannot find suitable count function for <class 'paddle.nn.layer.common.Identity'>. Treat it as zero FLOPs.
> Total Flops: 68982860800     Total Params: 41660694
> Out[1]: 68982860800
> 
> In [2]: import paddle
>    ...: from ppdet.core.workspace import load_config, merge_config
>    ...: from ppdet.core.workspace import create
>    ...:
>    ...: cfg_path = './configs/rtdetr/rtdetr_r18vd_6x_coco.yml'
>    ...: cfg = load_config(cfg_path)
>    ...: model = create(cfg.architecture)
>    ...:
>    ...: blob = {
>    ...:     'image': paddle.randn([1, 3, 640, 640]),
>    ...:     'im_shape': paddle.to_tensor([[640, 640]]),
>    ...:     'scale_factor': paddle.to_tensor([[1., 1.]])
>    ...: }
>    ...: paddle.flops(model, None, blob, custom_ops=None, print_detail=False)
>    ...:
> <class 'paddle.nn.layer.conv.Conv2D'>'s flops has been counted
> <class 'paddle.nn.layer.norm.BatchNorm2D'>'s flops has been counted
> <class 'paddle.nn.layer.pooling.AvgPool2D'>'s flops has been counted
> <class 'paddle.nn.layer.common.Linear'>'s flops has been counted
> <class 'paddle.nn.layer.common.Dropout'>'s flops has been counted
> Cannot find suitable count function for <class 'paddle.nn.layer.norm.LayerNorm'>. Treat it as zero FLOPs.
> Cannot find suitable count function for <class 'paddle.nn.layer.common.Embedding'>. Treat it as zero FLOPs.
> Cannot find suitable count function for <class 'ppdet.modeling.transformers.matchers.HungarianMatcher'>. Treat it as zero FLOPs.
> Total Flops: 30996761600     Total Params: 19504810
> Out[2]: 30996761600
> ```

真的有按照文档操作！！！！

1.按照文档替换相关位置的代码，
2.在RT-DETR/rtdetr_paddle下面新建flops.py文件，将文档中的运行代码全部复制进去，保存
3.执行flops.py ： python flops.py

紧接着就出现报错：
### File "flops.py", line 16, in
### paddle.flops(model, None,blob, custom_ops=None, print_detail=False)
### TypeError: flops() got multiple values for argument 'custom_ops'`


我真的不知道我哪里做错了，实在跑不出来。是要修改什么吗？

**Comment by JianyuChenyyds** [comment]
大佬，LCNet-1.0主干网络的预训练模型不能直接载入，2.5和1.5的都可以












陈建宇
***@***.***

山东科技大学




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月26日(周四) 中午11:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lyuwenyu/RT-DETR] flops计算代码跑不通 (Issue #72)




   
按照这个文档修改代码了嘛 
  
按这个代码修改后的FLOPs跟Model ZOO上对不上啊
  
请先理解 FLOPs和 MACs的区别

**Comment by Claraeunice** [comment]
> blob的内容上边不是有例子嘛

是不是代码忘记放了呀，没有例子呀？？？
