### ISSUE TITLE
use visdrone datasets

### ISSUE THREAD

**Issue by AINISHDD** [lyuwenyu/RT-DETR#98]
我前面使用yolov7,category_id是从0开始的到9.然后我继续使用这个格式的数据集放到rtdetr上的话我应该对于label2category_id以及其他地方应该改动哪里。我自己names = {
    1: 'pedestrain',
    2: 'people',
    3: 'bicycle',
    4: 'car',
    5: 'van',
    6: 'truck',
    7: 'tricycle',
    8: 'awning-tricycle',
    9: 'bus',
    10: 'motor'
}

label2category = {
    1: 0,
    2: 1,
    3: 2,
    4: 3,
    5: 4,
    6: 5,
    7: 6,
    8: 7,
    9: 8,
    10: 9
}然后 @property
    def mscoco_label_category_map(self, ):
        return {
            0: 0,
            1: 1,
            2: 2,
            3: 3,
            4: 4,
            5: 5,
            6: 6,
            7: 7,
            8: 8,
            9: 9

        }
最后还报错/home/liyihang/anaconda3/envs/redetr/bin/python /home/liyihang/redetr/rtdetr_pytorch/tools/train.py -c ../configs/rtdetr/rtdetr_r18vd_6x_coco.yml 
Not init distributed mode.
Start training
Load PResNet18 state_dict
Initial lr:  [1e-05, 1e-05, 0.0001, 0.0001]
loading annotations into memory...
Done (t=2.98s)
creating index...
index created!
loading annotations into memory...
Done (t=0.25s)
creating index...
index created!
number of params: 20094584
Traceback (most recent call last):
  File "/home/liyihang/redetr/rtdetr_pytorch/tools/train.py", line 39, in <module>
    main(args)
  File "/home/liyihang/redetr/rtdetr_pytorch/tools/train.py", line 27, in main
    solver.fit()
  File "/home/liyihang/redetr/rtdetr_pytorch/src/solver/det_solver.py", line 37, in fit
    train_stats = train_one_epoch(
  File "/home/liyihang/redetr/rtdetr_pytorch/src/solver/det_engine.py", line 35, in train_one_epoch
    for samples, targets in metric_logger.log_every(data_loader, print_freq, header):
  File "/home/liyihang/redetr/rtdetr_pytorch/src/misc/logger.py", line 215, in log_every
    for obj in iterable:
  File "/home/liyihang/anaconda3/envs/redetr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/liyihang/anaconda3/envs/redetr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/liyihang/anaconda3/envs/redetr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/liyihang/anaconda3/envs/redetr/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/liyihang/anaconda3/envs/redetr/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/liyihang/anaconda3/envs/redetr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/liyihang/anaconda3/envs/redetr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/liyihang/redetr/rtdetr_pytorch/src/data/coco/coco_dataset.py", line 39, in __getitem__
    img, target = super(CocoDetection, self).__getitem__(idx)
  File "/home/liyihang/anaconda3/envs/redetr/lib/python3.8/site-packages/torchvision/datasets/coco.py", line 48, in __getitem__
    image = self._load_image(id)
  File "/home/liyihang/anaconda3/envs/redetr/lib/python3.8/site-packages/torchvision/datasets/coco.py", line 40, in _load_image
    path = self.coco.loadImgs(id)[0]["file_name"]
  File "/home/liyihang/anaconda3/envs/redetr/lib/python3.8/site-packages/pycocotools/coco.py", line 227, in loadImgs
    return [self.imgs[id] for id in ids]
  File "/home/liyihang/anaconda3/envs/redetr/lib/python3.8/site-packages/pycocotools/coco.py", line 227, in <listcomp>
    return [self.imgs[id] for id in ids]
KeyError: '0'

**Comment by lyuwenyu** [comment]
https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetr_pytorch/src/data/coco/coco_dataset.py#L107  把这个-1去掉

**Comment by lyuwenyu** [comment]
你可以star一下这个repo  之后我会更新一下这块的易用性

**Comment by eagle-ming** [comment]
请问怎么解决啊
